swagger: "2.0"

info:
  title: "My first API"
  version: "1.0"

basePath: /v1.0

paths:
  /items/:
    get:
      responses:
        '200':
          description: 'Fetch a list of items'
          schema:
            type: array
            items:
              $ref: '#/definitions/Item'
  /battery/:
    get:
      responses:
        '200':
          description: 'get battery levels so far'
          schema:
            type: array
            items:
              $ref: '#/definitions/Battery'
    post:
      operationId: api.battery.addnew
      parameters:
        - in: body
          name: battery
          required: true
          schema:
              $ref: '#/definitions/Battery'
      responses:
        '201':
          description: 'successful'
          schema:
              $ref: '#/definitions/Battery'



definitions:
  Item:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name: { type: string }
  Battery:
   type: object
   required:
     - batlife
     - charging
     - timeleft
   properties:
     batlife:
       type: number
       format: float
     charging:
      type: boolean
     timeleft:
      type: number
      format: float
     time:
      type: string
      format: date-time
